terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
srun: error: cn10: task 0: Aborted (core dumped)
